build-image:
  services:
    - name: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/docker:24.0.2-dind
      alias: docker
      variables:
        DOCKER_TLS_CERTDIR: ''
  stage: build
  tags: [docker-executor]
  image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/docker:24.0.2
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
  variables:
    NO_PROXY: "docker"
    DOCKER_HOST: "tcp://docker:2375"
    GIT_LFS_SKIP_SMUDGE: "1"
  before_script:
    - apk --update add python3 py3-pip
    - python3 -m pip install poetry
    - which poetry
    - poetry self add poetry-multiproject-plugin
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY
    - ls -l projects/*/Dockerfile
    - dockerfiles=$(ls projects/*/Dockerfile)
    - for df in ${dockerfiles};
      do
        (
           project_name=$(basename $(dirname $df));
           docker build --tag $CI_REGISTRY_IMAGE:${project_name} -f $df .;
           docker push $CI_REGISTRY_IMAGE:${project_name};
        );
      done
