version: '3.4'

services:
  setup_service:
    build:
      context: ./setup_service/
    ports:
    - "8789:82"
    environment:
    - "http_proxy="
    - "https_proxy="
    - "HTTP_PROXY="
    - "HTTPS_PROXY="
    - "CONCIERGE_URL=http://concierge2"
    - "SLURK_HOST=http://slurk"
    - "TOKEN_SERVICE_URL=http://slurk-access-token-reader/token"
  concierge2:
    build:
      context: ./concierge2/
    volumes:
    - ./venv/lib/python3.11/site-packages/socketio/:/venv/lib/python3.11/site-packages/socketio/
    - ./venv/lib/python3.11/site-packages/engineio/:/venv/lib/python3.11/site-packages/engineio/
    environment:
    - "http_proxy="
    - "https_proxy="
    - "HTTP_PROXY="
    - "HTTPS_PROXY="
    - "SLURK_HOST=http://slurk"
    - "SLURK_PORT=80"
    - "PYTHONASYNCIODEBUG=1"
  slurk-access-token-reader:
    build:
      context: ./slurk_access_token_reader
    volumes:
    - logs:/log
    environment:
    - "http_proxy="
    - "https_proxy="
    - "HTTP_PROXY="
    - "HTTPS_PROXY="
    depends_on:
      - slurk

  slurk_delete_logs:
    image: alpine
    volumes:
    - logs:/log
    command: "sh -x -c 'rm -vf /log/slurk.log'"

  slurk:
    image: slurk
    entrypoint: /bin/bash
    command:
        - -c
        - >
          gunicorn
          --capture-output
          --error-logfile -
          --access-logfile -
          --log-level DEBUG
          -b :80
          -k geventwebsocket.gunicorn.workers.GeventWebSocketWorker
          "slurk:create_app()"
          |& tee /log/slurk.log
    volumes:
    - logs:/log
    - ./venv/lib/python3.11/site-packages/socketio/:/usr/local/lib/python3.9/site-packages/socketio/
    - ./venv/lib/python3.11/site-packages/engineio/:/usr/local/lib/python3.9/site-packages/engineio/
    ports:
    - "8788:80"
    environment:
    - "http_proxy="
    - "https_proxy="
    - "HTTP_PROXY="
    - "HTTPS_PROXY="
    - "FLASK_ENV=development"
    depends_on:
      slurk_delete_logs:
        condition: service_completed_successfully

volumes:
  logs:
