version: '3.4'

services:
  setup_service:
    image: registry.ethz.ch/sis/slurk-chat-bot-setup-descil:setup_service
    build:
      context: ./projects/setup_service
    ports:
    - "8789:81"
    environment:
    - "http_proxy="
    - "https_proxy="
    - "HTTP_PROXY="
    - "HTTPS_PROXY="
    - "CONCIERGE_URL=http://concierge_plus:82"
    - "SLURK_HOST=http://slurk:80"
    - "TOKEN_SERVICE_URL=http://slurk-access-token-reader:83/token"
    - "ADMIN_TOKEN=666"

  concierge_plus:
    image: registry.ethz.ch/sis/slurk-chat-bot-setup-descil:concierge_plus
    build:
      context: ./projects/concierge_plus/
    environment:
    - "http_proxy="
    - "https_proxy="
    - "HTTP_PROXY="
    - "HTTPS_PROXY="
    - "SLURK_HOST=http://slurk"
    - "SLURK_PORT=80"
    - "PYTHONASYNCIODEBUG=1"

  slurk:
    image: registry.ethz.ch/sis/slurk-descil:slurk-descil
    entrypoint: /bin/bash
    command:
        - -c
        - >
          gunicorn
          --capture-output
          --error-logfile -
          --access-logfile -
          --log-level DEBUG
          -b :80
          -k geventwebsocket.gunicorn.workers.GeventWebSocketWorker
          "slurk:create_app()"
          |& tee /log/slurk.log
    ports:
    - "8788:80"
    environment:
    - "http_proxy="
    - "https_proxy="
    - "HTTP_PROXY="
    - "HTTPS_PROXY="
    - "ADMIN_TOKEN=666"
