version: '3.4'

services:
  setup_service:
    image: registry.ethz.ch/sis/slurk-chat-bot-setup-descil:setup_service
    build:
      dockerfile: ./projects/setup_service/Dockerfile
    ports:
    - "8789:81"
    environment:
    - "http_proxy="
    - "https_proxy="
    - "HTTP_PROXY="
    - "HTTPS_PROXY="
    - "CONCIERGE_URL=http://concierge_plus:82"
    - "SLURK_HOST=http://slurk"
    - "SLURK_PORT=80"
    - "ADMIN_TOKEN=666"

  concierge_plus:
    image: registry.ethz.ch/sis/slurk-chat-bot-setup-descil:concierge_plus
    build:
      dockerfile: ./projects/concierge_plus/Dockerfile
    environment:
    - "http_proxy="
    - "https_proxy="
    - "HTTP_PROXY="
    - "HTTPS_PROXY="
    - "SLURK_HOST=http://slurk"
    - "SLURK_PORT=80"
    - "PYTHONASYNCIODEBUG=1"
    - "PYTHONUNBUFFERED=1"
    - "CHATBOT_URL=http://chatbot:84"
    - "MANAGERBOT_URL=http://managerbot:85"

  chatbot:
    build:
      dockerfile: ./projects/chatbot/Dockerfile
    environment:
    - "SLURK_HOST=http://slurk"
    - "SLURK_PORT=80"
    - "PYTHONASYNCIODEBUG=1"
    - "PYTHONUNBUFFERED=1"
    - "AZURE_OPENAI_ENDPOINT=https://css-openai.openai.azure.com/"
    - "AZURE_OPENAI_API_KEY=***REMOVED***"
    - "AZURE_OPENAI_API_VERSION=2023-12-01-preview"
    - "AZURE_OPENAI_MODEL=css-openai-gpt35"
    - "AZURE_OPENAI_MODEL_TEMPERATURE=0.9"
    - "AZURE_OPENAI_MODEL_MAX_TOKENS=80"
    - "POLYBOX_URL=https://polybox.ethz.ch/index.php/s/MAZlGw1ZPBFYUJn/download"
    - "PROMPT_API_URL=https://slurkexp.vlab.ethz.ch/api/fullprompt/"

  managerbot:
    build:
      dockerfile: ./projects/managerbot//Dockerfile
    environment:
    - "http_proxy="
    - "https_proxy="
    - "HTTP_PROXY="
    - "HTTPS_PROXY="
    - "SLURK_HOST=http://slurk"
    - "SLURK_PORT=80"
    - "PYTHONASYNCIODEBUG=1"
    - "PYTHONUNBUFFERED=1"

  slurk:
    image: slurk # registry.ethz.ch/sis/slurk-descil:slurk-descil
    entrypoint: /bin/bash
    command:
        - -c
        - >
          gunicorn
          --capture-output
          --error-logfile -
          --access-logfile -
          --log-level DEBUG
          -b :80
          -k geventwebsocket.gunicorn.workers.GeventWebSocketWorker
          "slurk:create_app()"
          |& tee /log/slurk.log
    ports:
    - "8788:80"
    environment:
    - "http_proxy="
    - "https_proxy="
    - "HTTP_PROXY="
    - "HTTPS_PROXY="
    - "ADMIN_TOKEN=666"
